version: '3'
services:
  chatbot:
    build:
      context: .
      dockerfile: docker/Rasa.dockerfile
    container_name: rasa
    networks: 
      - rasa-network
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"

  action_server:
    build:
      context: .
      dockerfile: docker/Actions.dockerfile
    image: rasa-action-server
    container_name: ractions
    networks: 
      - rasa-network
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    container_name: rasa-duckling
    networks: 
      - rasa-network
    ports:
      - "8000:8000"

  mongodb:
    image: mongo
    container_name: db
    networks: 
      - rasa-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test

networks: 
    rasa-network:
        driver: bridge